[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/protected"
  to = "/"
  force = true
  status = 200
  conditions = {Role = ["user"]}